apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: shardclusters.bedrock.dev
spec:
  group: bedrock.dev
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              discord_token_secret:
                type: string
                description: "Name of the Kubernetes secret containing the Discord bot token"
              nats_url:
                type: string
                description: "URL for the NATS server"
              image:
                type: string
                description: "Docker image for the stratum bot instances"
              replicas_per_shard_group:
                type: integer
                description: "Number of replicas per shard group"
                minimum: 1
              shards_per_replica:
                type: integer
                description: "Number of shards per replica"
                minimum: 1
              reshard_interval_hours:
                type: integer
                description: "Interval in hours between automatic reshards"
                minimum: 1
            required:
            - discord_token_secret
            - nats_url
            - image
            - replicas_per_shard_group
            - shards_per_replica
            - reshard_interval_hours
          status:
            type: object
            properties:
              current_shards:
                type: integer
                description: "Current number of shards"
              last_reshard:
                type: string
                format: date-time
                description: "Timestamp of the last reshard operation"
              shard_groups:
                type: array
                items:
                  type: object
                  properties:
                    deployment_name:
                      type: string
                    shard_start:
                      type: integer
                    shard_end:
                      type: integer
                    replicas:
                      type: integer
              phase:
                type: string
                description: "Current phase of the shard cluster"
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: shardclusters
    singular: shardcluster
    kind: ShardCluster
    shortNames:
    - sc
