[package]
name = "crust-nats"
version = "0.1.0"
edition = "2024"

[dependencies]
crust-types = { path = "../crust-types" }
async-nats = { workspace = true }
backon = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
