# Development values for nats-cluster
# Optimized for local development and testing

nats:
  # Use lighter image for dev
  image:
    repository: nats
    tag: "2.10.7-alpine"
    pullPolicy: IfNotPresent

  # Smaller cluster for dev
  cluster:
    enabled: false  # Disable clustering for single node dev
    replicas: 1  # Single node for dev
    name: "nats-dev"

  # JetStream with minimal storage
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 1Gi  # Smaller storage for dev
        storageClassName: ""  # Use default storage class

  # Minimal resource requirements
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

  # Service configuration for dev
  service:
    type: NodePort  # Easier access from outside cluster
    ports:
      client: 4222
      cluster: 6222
      monitor: 8222

  # Minimal persistence
  persistence:
    enabled: true
    size: 1Gi
    storageClass: ""  # Use default
    accessMode: ReadWriteOnce

  # Disable PDB for dev (not needed with single replica)
  podDisruptionBudget:
    enabled: false

  # Relaxed security for dev
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true

  config:
    cluster:
      enabled: false  # Disable clustering for single node
      port: 6222
    merge:
      jetstream:
        enabled: true
        store_dir: "/data"
        max_memory_store: "256MB"
        max_file_store: "1GB"
      
      log_level: "debug"  # More verbose logging for dev
      port: 4222
      http_port: 8222

# Disable monitoring for dev
monitoring:
  enabled: false

# No network policies for dev
networkPolicy:
  enabled: false

# Optional ingress for dev (disabled by default)
ingress:
  enabled: false
