# Default values for nats-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nats:
  # NATS Server configuration
  image:
    repository: nats
    tag: "2.10.7-alpine"
    pullPolicy: IfNotPresent

  # Cluster configuration
  cluster:
    enabled: true
    replicas: 3
    name: "nats-cluster"

  # JetStream configuration
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 10Gi
        storageClassName: "standard"

  # NATS configuration
  config:
    cluster:
      enabled: true
      port: 6222
    merge:
      # Enable JetStream
      jetstream:
        enabled: true
        store_dir: "/data"
        max_memory_store: 1GB
        max_file_store: 10GB
      
      # Logging configuration
      log_level: "info"
      
      # Client port configuration
      port: 4222
      
      # HTTP monitoring port
      http_port: 8222

  # Resource limits
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  # Service configuration
  service:
    type: ClusterIP
    ports:
      client: 4222
      cluster: 6222
      monitor: 8222

  # Persistence for JetStream
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "standard"
    accessMode: ReadWriteOnce

  # Pod disruption budget
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1

  # Security context
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsNonRoot: true

# Additional configurations
monitoring:
  enabled: true
  serviceMonitor:
    enabled: false
    namespace: ""
    labels: {}

# Network policies
networkPolicy:
  enabled: false

# Ingress configuration (optional)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: nats.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
