[package]
name = "stratum-coordination"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = { workspace = true }
futures-util = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }