FROM rust:1.87.0 AS builder

WORKDIR /app

COPY bot/crust ./crust-workspace
COPY bot/util ./util

WORKDIR /app/crust-workspace

RUN cargo build --release

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/crust-workspace/target/release/crust /usr/local/bin/crust

EXPOSE 8080

CMD ["crust"]
