apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nats-cluster.fullname" . }}
  labels:
    {{- include "nats-cluster.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "nats-cluster.fullname" . }}-headless
  replicas: {{ .Values.nats.cluster.replicas | default 3 }}
  selector:
    matchLabels:
      {{- include "nats-cluster.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nats-cluster.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nats.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: nats
        image: "{{ .Values.nats.image.repository }}:{{ .Values.nats.image.tag }}"
        imagePullPolicy: {{ .Values.nats.image.pullPolicy }}
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        command:
        - "nats-server"
        - "--config"
        - "/etc/nats-config/nats.conf"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_ADVERTISE
          value: "$(POD_NAME).{{ include "nats-cluster.fullname" . }}-headless.$(POD_NAMESPACE).svc.cluster.local"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nats-config
        {{- if .Values.nats.jetstream.enabled }}
        - name: jetstream-storage
          mountPath: /data
        {{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
        {{- with .Values.nats.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "nats-cluster.fullname" . }}-config
  {{- if .Values.nats.jetstream.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: jetstream-storage
    spec:
      accessModes:
      - {{ .Values.nats.persistence.accessMode | default "ReadWriteOnce" }}
      {{- if .Values.nats.persistence.storageClass }}
      storageClassName: {{ .Values.nats.persistence.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.nats.persistence.size | default "10Gi" }}
  {{- end }}
