[package]
name = "stratum-discord"
version = "0.1.0"
edition = "2021"

[dependencies]
stratum-config = { path = "../stratum-config" }
anyhow = { workspace = true }
twilight-gateway = { workspace = true }
twilight-model = { workspace = true }
