[package]
name = "crust-scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
crust-types = { path = "../crust-types" }
chrono = { workspace = true }
kube = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
