[package]
name = "stratum-nats"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-nats = { workspace = true }
backon = { workspace = true }
tracing = { workspace = true }
