apiVersion: apps/v1
kind: Deployment
metadata:
  name: twilight-gateway-proxy
  namespace: bedrock
  labels:
    app: twilight-gateway-proxy
spec:
  replicas: 3  # Production: Multiple replicas for high availability
  selector:
    matchLabels:
      app: twilight-gateway-proxy
  template:
    metadata:
      labels:
        app: twilight-gateway-proxy
    spec:
      containers:
      - name: twilight-gateway-proxy
        image: ghcr.io/twilight-rs/http-proxy:latest
        imagePullPolicy: Always  # Production: Always pull for latest security updates
        ports:
        - containerPort: 80  # The proxy actually listens on port 80
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-token
              key: token
        - name: RUST_LOG
          value: "info"  # Production: Less verbose logging
        - name: PROXY_TIMEOUT
          value: "30"    # Production: 30 second timeout
        - name: MAX_CONNECTIONS
          value: "1000"  # Production: Increased connection limit
        resources:
          requests:
            memory: "512Mi"  # Production: Increased memory for better performance
            cpu: "500m"      # Production: Increased CPU for better performance
          limits:
            memory: "2Gi"    # Production: Higher memory limit
            cpu: "1000m"     # Production: Higher CPU limit
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: twilight-gateway-proxy
  namespace: bedrock
spec:
  selector:
    app: twilight-gateway-proxy  # Fixed: should match the deployment label
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
